    - &Restaurant
        # DefaultOrg defines the organization which is used in the sampleconfig
        # of the fabric.git development environment
        Name: RestaurantMSP

        # ID to load the MSP definition as
        ID: RestaurantMSP

        MSPDir: crypto-config/peerOrganizations/restaurant.example.com/msp

        AnchorPeers:
            # AnchorPeers defines the location of peers which can be used
            # for cross org gossip communication.  Note, this value is only
            # encoded in the genesis block in the Application section context
            - Host: peer0.restaurant.example.com
              Port: 7051